name = "Fabulous Voxy Voice"
author = "robotkoer, Json17"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e42690a6152ae1e999ab716fe73c9c6e0194e19ce078006e68ab3614a807206a"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
