name = "Fabulous Voxy Voice"
author = "robotkoer, Json17"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86353693fdb4d4310820f8b9228c2935aa1239c42df38a928729c10b28fc0c9b"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
