name = "Fabulous Voxy Voice"
author = "robotkoer, Json17"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f908a73b5926748265b20bcc6488ea0e7f44bff6a54497f7ed5568d15e7a230e"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
